version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123elma123
      MYSQL_DATABASE: community_application
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql_scripts/create.sql:/docker-entrypoint-initdb.d/create.sql
    command: --default-authentication-plugin=mysql_native_password

  springboot-app:
    image: 099000/community-application:latest
    container_name: springboot-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: community_application
      MYSQL_USER: root
      MYSQL_PASSWORD: 123elma123
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:

volumes:
  mysql-data:
